language: elixir
elixir: 
  - '1.7'
otp_release:
  - '21.3.3'
os:
  - linux
  #- osx # elixir is not available for macOS (might be able to do a workaround installing asdf)
env:
  global:
    - HEX_USERNAME=spencerdcarlson
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
before_install:
  - git init ${TRAVIS_BUILD_DIR}/dev/sandbox
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile  
script:
  - mix format --check-formatted
  - mix credo --strict  
  - mix test
deploy:
  provider: script
  script: >-
    rm priv/husky && 
    MIX_ENV=prod mix escript.build &&
    mix deps.get &&
    mix hex.config username "$HEX_USERNAME" &&
    (mix hex.config encrypted_key "$HEX_ENCRYPTED_KEY" > /dev/null 2>&1) &&
    (echo "$HEX_PASSPHRASE"\\nY | mix hex.publish)
  on:
    tags: true
