language: bash
os:
  - linux
  - osx
env:
  global:
    - MIX_ENV=test
    - ASDF_VERISON=v0.7.2  
cache:
  directories:
    - _build
    - deps
    - ${HOME}/.asdf
before_cache:
    - rm ${TRAVIS_BUILD_DIR}/_build/test/lib/husky/.mix/compile.elixir
    - cat ${HOME}/.asdf/.git/logs/HEAD
    - (cd ${HOME}/.asdf && git rev-parse --abbrev-ref HEAD | grep "heads/${ASDF_VERSION}" && echo "correct version" || echo "wrong version")
before_install: >-
  git init ${TRAVIS_BUILD_DIR}/dev/sandbox &&
  git clone https://github.com/asdf-vm/asdf.git ${HOME}/.asdf || true &&
  (cd ${HOME}/.asdf && git rev-parse --abbrev-ref HEAD && git checkout "$(git describe --abbrev=0 --tags)") &&
  . ${HOME}/.asdf/asdf.sh &&
  asdf update &&
  asdf plugin-add elixir || true &&
  asdf plugin-add erlang || true &&
  travis_wait asdf install
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile  
script:
  - mix format --check-formatted
  - mix credo --strict  
  - mix test
deploy:
  provider: script
  script: >-
    git init ${TRAVIS_BUILD_DIR}/../../ &&
    rm -f priv/husky && 
    MIX_ENV=prod mix deps.get &&
    MIX_ENV=prod mix escript.build &&
    MIX_ENV=dev mix hex.publish --yes &&
    git clean -f
  on:
    tags: true
