language: elixir
elixir: 
  - '1.7'
otp_release:
  - '21.3.3'
os:
  - linux
  #- osx # elixir is not available for macOS (might be able to do a workaround installing asdf)
env:
  global:
    - HEX_USERNAME=spencerdcarlson
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
before_install:
  - git init ${TRAVIS_BUILD_DIR}/dev/sandbox
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile  
script:
  - mix format --check-formatted
  - mix credo --strict  
  - mix test
deploy:
  provider: script
  script: >-
    rm -f priv/husky && 
    MIX_ENV=prod mix deps.get &&
    MIX_ENV=prod mix escript.build &&
    mix hex.publish &&
    mix clean &&
    mix deps.clean --all
    rm -f priv/husky
  on:
    tags: true
