language: elixir
elixir: 
  - '1.7'
otp_release:
  - '21.3.3'
os:
  - linux
  #- osx
before_install:
  - git init ${TRAVIS_BUILD_DIR}/dev/sandbox
  - git init ${TRAVIS_BUILD_DIR}../../
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile  
script:
   mix test
